site_name: Unofficial Paizo Guides
site_url: https://doughahn.github.io/unofficial-opf-guides/
nav:
    - Organized Play:
      - Organized Play 101: organized-play/org-play.md
      - 2E Errata: organized-play/2e-FAQ.md
      - PFS FaQ: organized-play/pfs-faq.md
      - PFS Character Options: organized-play/resources-options.md
      - PFS Boons: organized-play/2e-boons.md
      - PFS Scenario List: organized-play/2e-scenarios.md
      - SFS Scenario List: organized-play/starfinder-scenarios.md
    - Using Warhorn:
      - For Players: warhorn/warhorn.md
      - For Organizers: warhorn/warhorn-for-organizers.md
    - Online Gaming:
      - Choosing a VTT: vtt/vtts-overview.md
      - Creating Assets: vtt/assets.md
      - Splitting Chronicles: vtt/splitting-chronicles.md
    - Play by Post:
      - Paizo Play by Post: pbp/play-by-post.md
      - Paizo Avatar Gallery: pbp/avatar-inventory.md
    - Roll20:
      - Free account macros: roll20/roll20-basics.md
      - Advanced macros: roll20/advanced-macros.md
    - Foundry:
      - Basics: foundry/foundry-basics.md
    - Paizo Website:
      - Payment Methods: paizo/payment-methods.md
    - External Resources: 
      - General Resources:
        - PFS Prep: http://pfsprep.com/e107_plugins/forum/forum.php
        - Org Play 2E Guide: https://www.organizedplayfoundation.org/Lorespire/Pathfinder-Society-(Second-Edition)-Guide-to-Organized-Play
        - Org Play SFS Guide: https://www.organizedplayfoundation.org/Lorespire/Starfinder-Society-Guide-to-Organized-Play
        - VO Handbook: https://www.organizedplayfoundation.org/Lorespire/VO-Handbook
      - Roll20:
        - Flutters Guide to (Roll20): https://docs.google.com/document/d/1mBGmsC5te1z6Sx2c2SFDglzAegPWFxH6znF6yH9wCpw/edit
        - How to make a Roll20 Table: https://docs.google.com/document/d/1xmhyrZetSM09iORM2rnFQiQemA9m1Uhdk3DB_TKrctk/edit
        - Macro Cheat Sheet: https://wiki.roll20.net/Pathfinder_Second_Edition_Official#Repeating_Sections
        - Starfinder Simple Sheet: https://docs.google.com/document/d/1YLbFvfsm4keYKt87tRzgAgMMEqgUQCTVpmCMnsJEHRE/edit
        - PC Woof: https://docs.google.com/document/d/1evHzA_NH3GrlI0G_aPokzUViuX7nyQCD7yER9n7IHaU/edit
      - Second Edition:
        - Treasure Table: https://docs.google.com/spreadsheets/d/1BfUZXtaIVuBp6qIsVvPQW-45NEpv3VZUFBGCqsOAWc4/edit#gid=1468913539
        - How to Craft in PFS: https://docs.google.com/document/d/1jkTztvXwTnqBLoFGW0ZFQIwVSugVwk3VKomhLK5Nr48/edit?usp=sharing
        - Gisher's Goodies: https://docs.google.com/document/d/1JTL87bsQEO6q_qOF0cmnhwYkwstac5rnyvHOSCC0b8Q/edit
        - Guide to the Guides: https://zenithgames.blogspot.com/2019/09/pathfinder-2nd-edition-guide-to-guides.html
      - Starfinder:
        - Guide for Newbies: https://docs.google.com/document/d/10YlSEsJm6kOcibHrEPjVEDgHp7A1hXmV6JUaAh0Qnq0/edit
        - Build a SFS Character: https://docs.google.com/document/d/1r_Y0ZVgNoZJQ4Z4rtTlHSd4_kqG8YAr14kTqBwun00I/edit
    # - Foundry: foundry.md
    # - Slides: slides.md 
    # - Suggested-rulings: suggested-rulings.md
    # - Class & Skill Guides: guides.md 
theme:
  name: 'material'
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - toc.follow
    - navigation.sections
    - navigation.expand
    - content.tabs.link 
    - navigation.indexes
  hide:
    - navigation
  logo: 
    'https://gmdoug.sfo3.digitaloceanspaces.com/glyph.svg'
extra:
  version:
    provider: mike
repo_name: doughahn/unofficial-opf-guides
repo_url: https://github.com/doughahn/unofficial-opf-guides
extra_css:
    - css/extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/featherlight/v.1.7.14/featherlight.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/featherlight/1.7.13/featherlight.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - def_list
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - featherlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 2
      permalink: 6
      permalink: ⚑
plugins:
  - search
  - table-reader:
      data_path: "docs/assets"
  - redirects:
      redirect_maps:
        'org-play.md': 'organized-play/org-play.md'
        '2e-FAQ.md': 'organized-play/2e-FAQ.md'
        'pfs-faq.md': 'organized-play/pfs-faq.md'
        '2e-boons.md': 'organized-play/2e-boons.md'
        'warhorn.md': 'warhorn/warhorn.md'
        'warhorn-for-organizers.md': 'warhorn/warhorn-for-organizers.md'
        'vtts-overview.md': 'vtt/vtts-overview.md'
        'assets.md': 'vtt/assets.md'
        'splitting-chronicles.md': 'vtt/splitting-chronicles.md'
        'roll20-basics.md': 'roll20/roll20-basics.md'
        'advanced-macros.md': 'roll20/advanced-macros.md'
        'foundry-basics.md': 'foundry/foundry-basics.md'
        'play-by-post.md': 'pbp/play-by-post.md'
        'other-guides.md': 'other-guides/other-guides.md'
copyright: 'Copyright Statement: This website uses trademarks and/or copyrights owned by <a href="https://paizo.com/">Paizo Inc</a>., which are used under Paizo’s Community Use Policy. We are expressly prohibited from charging you to use or access this content. This website is not published, endorsed, or specifically approved by Paizo Inc. For more information about Paizo’s Community Use Policy, please visit <a href="https://paizo.com/community/communityuse">paizo.com/communityuse</a>. For more information about Paizo Inc. and Paizo Organized Play Programs, please visit paizo.com.'