site_name: Unofficial Paizo Guides
site_url: https://doughahn.github.io/unofficial-opf-guides/
nav:
    - Organized Play:
      - Organized Play 101: organized-play/org-play.md
      - 2E Errata: organized-play/2e-FAQ.md
      - PFS FaQ: organized-play/pfs-faq.md
      - PFS Boons: organized-play/2e-boons.md
      - PFS Resources & Options: organized-play/resources-options.md
      - 2E Scenarios: organized-play/2e-scenarios.md
      - Starfinder Scenarios: organized-play/starfinder-scenarios.md
    - Using Warhorn:
      - For Players: warhorn/warhorn.md
      - For Organizers: warhorn/warhorn-for-organizers.md
    - VTTs & Assets:
      - Choosing a VTT: vtt/vtts-overview.md
      - Creating Assets: vtt/assets.md
      - Splitting Chronicles: vtt/splitting-chronicles.md
    - Play by Post:
      - Paizo Play by Post: pbp/play-by-post.md
      - Paizo Avatar Gallery: pbp/avatar-inventory.md
    - Roll20:
      - Free account macros: roll20/roll20-basics.md
      - Advanced macros: roll20/advanced-macros.md
    - Foundry:
      - Basics: foundry/foundry-basics.md
    - Paizo Website:
      - Payment Methods: paizo/payment-methods.md
    - More Guides: other-guides/other-guides.md
    # - Foundry: foundry.md
    # - Slides: slides.md 
    # - Suggested-rulings: suggested-rulings.md
    # - Class & Skill Guides: guides.md 
theme:
  name: 'material'
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - toc.follow
    - navigation.sections
    - navigation.expand
    - content.tabs.link
    - navigation.indexes
  hide:
    - navigation
  logo: 
    'https://gmdoug.sfo3.digitaloceanspaces.com/glyph.svg'
extra:
  version:
    provider: mike
repo_name: doughahn/unofficial-opf-guides
repo_url: https://github.com/doughahn/unofficial-opf-guides
extra_css:
    - css/extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/featherlight/v.1.7.14/featherlight.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/featherlight/1.7.13/featherlight.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - def_list
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - featherlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 3
      permalink: 6
      permalink: ⚑
plugins:
  - search
  - table-reader:
      data_path: "docs/assets"
  - redirects:
      redirect_maps:
        'org-play.md': 'organized-play/org-play.md'
        '2e-FAQ.md': 'organized-play/2e-FAQ.md'
        'pfs-faq.md': 'organized-play/pfs-faq.md'
        '2e-boons.md': 'organized-play/2e-boons.md'
        'warhorn.md': 'warhorn/warhorn.md'
        'warhorn-for-organizers.md': 'warhorn/warhorn-for-organizers.md'
        'vtts-overview.md': 'vtt/vtts-overview.md'
        'assets.md': 'vtt/assets.md'
        'splitting-chronicles.md': 'vtt/splitting-chronicles.md'
        'roll20-basics.md': 'roll20/roll20-basics.md'
        'advanced-macros.md': 'roll20/advanced-macros.md'
        'foundry-basics.md': 'foundry/foundry-basics.md'
        'play-by-post.md': 'pbp/play-by-post.md'
        'other-guides.md': 'other-guides/other-guides.md'
copyright: 'Copyright Statement: This website uses trademarks and/or copyrights owned by <a href="https://paizo.com/">Paizo Inc</a>., which are used under Paizo’s Community Use Policy. We are expressly prohibited from charging you to use or access this content. This website is not published, endorsed, or specifically approved by Paizo Inc. For more information about Paizo’s Community Use Policy, please visit <a href="https://paizo.com/community/communityuse">paizo.com/communityuse</a>. For more information about Paizo Inc. and Paizo Organized Play Programs, please visit paizo.com.'